on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c(
            "cowplot",
            "devtools",
            "distill",
            "here",
            "htmltools",
            "janitor",
            "knitr",
            "metathis",
            "postcards",
            "remotes",
            "rmarkdown",
            "roxygen2",
            "tidyverse",
            "viridis",
            "yaml"))
          devtools::install_github("EllaKaye/distilltools")
          devtools::install_github("hadley/emo")
          devtools::install_github("rstudio/fontawesome")
          devtools::install_github("haozhu233/kableExtra")
        shell: Rscript {0}

      - name: Render Site
        run: |
          source("build_site.R")
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
